// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuln4NI5HH-sxkeHWOurtpRoGnjoTWhOM',
    appId: '1:252221186562:web:022caea20d2655ff417d1b',
    messagingSenderId: '252221186562',
    projectId: 'automacao-residencial-227d5',
    authDomain: 'automacao-residencial-227d5.firebaseapp.com',
    storageBucket: 'automacao-residencial-227d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfp_7GFGHt5ueoHfkpMC2HOF_qHxhzUFM',
    appId: '1:252221186562:android:b638361fdcfce7c2417d1b',
    messagingSenderId: '252221186562',
    projectId: 'automacao-residencial-227d5',
    storageBucket: 'automacao-residencial-227d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWbQyGAaMxXjXkBtCJkf3rjAKZYhFXTxM',
    appId: '1:252221186562:ios:0f76c91157994c6f417d1b',
    messagingSenderId: '252221186562',
    projectId: 'automacao-residencial-227d5',
    storageBucket: 'automacao-residencial-227d5.appspot.com',
    iosClientId: '252221186562-47mald07d8msato7ndgfakhv2l0s4v0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.automcaoResidencial',
  );
}
